"""Create application table

Revision ID: 85806be46819
Revises: 9a947cf59435
Create Date: 2024-08-15 19:54:34.987561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85806be46819'
down_revision = '9a947cf59435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
